CREATE TABLE Series(id INTEGER PRIMARY KEY, author TEXT, sub-genres);
CREATE TABLE Sub-Genres(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE Authors(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE Books(id INTEGER PRIMARY KEY, title TEXT, year INTEGER);
CREATE TABLE Characters(id INTEGER PRIMARY KEY,  name TEXT, motto TEXT, species TEXT);
